/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated.index'
import { Route as AuthenticatedTeacherRouteImport } from './routes/_authenticated.teacher'
import { Route as AuthenticatedStudentRouteImport } from './routes/_authenticated.student'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated.profile'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated.onboarding'
import { Route as AuthenticatedTeacherIndexRouteImport } from './routes/_authenticated.teacher.index'
import { Route as AuthenticatedStudentIndexRouteImport } from './routes/_authenticated.student.index'
import { Route as AuthenticatedTeacherPlansRouteImport } from './routes/_authenticated.teacher.plans'
import { Route as AuthenticatedTeacherMaterialsRouteImport } from './routes/_authenticated.teacher.materials'
import { Route as AuthenticatedTeacherDiagnosticRouteImport } from './routes/_authenticated.teacher.diagnostic'
import { Route as AuthenticatedTeacherAssistantRouteImport } from './routes/_authenticated.teacher.assistant'
import { Route as AuthenticatedTeacherAnalyticsRouteImport } from './routes/_authenticated.teacher.analytics'
import { Route as AuthenticatedStudentProgressRouteImport } from './routes/_authenticated.student.progress'
import { Route as AuthenticatedStudentPathRouteImport } from './routes/_authenticated.student.path'
import { Route as AuthenticatedStudentMaterialsRouteImport } from './routes/_authenticated.student.materials'
import { Route as AuthenticatedStudentLessonsRouteImport } from './routes/_authenticated.student.lessons'
import { Route as AuthenticatedStudentDiagnosticRouteImport } from './routes/_authenticated.student.diagnostic'
import { Route as AuthenticatedStudentCalendarRouteImport } from './routes/_authenticated.student.calendar'
import { Route as AuthenticatedStudentAssistantRouteImport } from './routes/_authenticated.student.assistant'
import { Route as AuthenticatedLessonLessonIdRouteImport } from './routes/_authenticated.lesson.$lessonId'
import { Route as AuthenticatedTeacherStudentsIndexRouteImport } from './routes/_authenticated.teacher.students.index'
import { Route as AuthenticatedTeacherStudentsStudentIdRouteImport } from './routes/_authenticated.teacher.students.$studentId'
import { Route as AuthenticatedStudentTopicsTopicIdRouteImport } from './routes/_authenticated.student.topics.$topicId'
import { Route as AuthenticatedStudentSubjectsSubjectIdRouteImport } from './routes/_authenticated.student.subjects.$subjectId'
import { Route as AuthenticatedStudentDiagnosticSessionIdRouteImport } from './routes/_authenticated.student.diagnostic.$sessionId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTeacherRoute = AuthenticatedTeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStudentRoute = AuthenticatedStudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTeacherIndexRoute =
  AuthenticatedTeacherIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedTeacherRoute,
  } as any)
const AuthenticatedStudentIndexRoute =
  AuthenticatedStudentIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedStudentRoute,
  } as any)
const AuthenticatedTeacherPlansRoute =
  AuthenticatedTeacherPlansRouteImport.update({
    id: '/plans',
    path: '/plans',
    getParentRoute: () => AuthenticatedTeacherRoute,
  } as any)
const AuthenticatedTeacherMaterialsRoute =
  AuthenticatedTeacherMaterialsRouteImport.update({
    id: '/materials',
    path: '/materials',
    getParentRoute: () => AuthenticatedTeacherRoute,
  } as any)
const AuthenticatedTeacherDiagnosticRoute =
  AuthenticatedTeacherDiagnosticRouteImport.update({
    id: '/diagnostic',
    path: '/diagnostic',
    getParentRoute: () => AuthenticatedTeacherRoute,
  } as any)
const AuthenticatedTeacherAssistantRoute =
  AuthenticatedTeacherAssistantRouteImport.update({
    id: '/assistant',
    path: '/assistant',
    getParentRoute: () => AuthenticatedTeacherRoute,
  } as any)
const AuthenticatedTeacherAnalyticsRoute =
  AuthenticatedTeacherAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedTeacherRoute,
  } as any)
const AuthenticatedStudentProgressRoute =
  AuthenticatedStudentProgressRouteImport.update({
    id: '/progress',
    path: '/progress',
    getParentRoute: () => AuthenticatedStudentRoute,
  } as any)
const AuthenticatedStudentPathRoute =
  AuthenticatedStudentPathRouteImport.update({
    id: '/path',
    path: '/path',
    getParentRoute: () => AuthenticatedStudentRoute,
  } as any)
const AuthenticatedStudentMaterialsRoute =
  AuthenticatedStudentMaterialsRouteImport.update({
    id: '/materials',
    path: '/materials',
    getParentRoute: () => AuthenticatedStudentRoute,
  } as any)
const AuthenticatedStudentLessonsRoute =
  AuthenticatedStudentLessonsRouteImport.update({
    id: '/lessons',
    path: '/lessons',
    getParentRoute: () => AuthenticatedStudentRoute,
  } as any)
const AuthenticatedStudentDiagnosticRoute =
  AuthenticatedStudentDiagnosticRouteImport.update({
    id: '/diagnostic',
    path: '/diagnostic',
    getParentRoute: () => AuthenticatedStudentRoute,
  } as any)
const AuthenticatedStudentCalendarRoute =
  AuthenticatedStudentCalendarRouteImport.update({
    id: '/calendar',
    path: '/calendar',
    getParentRoute: () => AuthenticatedStudentRoute,
  } as any)
const AuthenticatedStudentAssistantRoute =
  AuthenticatedStudentAssistantRouteImport.update({
    id: '/assistant',
    path: '/assistant',
    getParentRoute: () => AuthenticatedStudentRoute,
  } as any)
const AuthenticatedLessonLessonIdRoute =
  AuthenticatedLessonLessonIdRouteImport.update({
    id: '/lesson/$lessonId',
    path: '/lesson/$lessonId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTeacherStudentsIndexRoute =
  AuthenticatedTeacherStudentsIndexRouteImport.update({
    id: '/students/',
    path: '/students/',
    getParentRoute: () => AuthenticatedTeacherRoute,
  } as any)
const AuthenticatedTeacherStudentsStudentIdRoute =
  AuthenticatedTeacherStudentsStudentIdRouteImport.update({
    id: '/students/$studentId',
    path: '/students/$studentId',
    getParentRoute: () => AuthenticatedTeacherRoute,
  } as any)
const AuthenticatedStudentTopicsTopicIdRoute =
  AuthenticatedStudentTopicsTopicIdRouteImport.update({
    id: '/topics/$topicId',
    path: '/topics/$topicId',
    getParentRoute: () => AuthenticatedStudentRoute,
  } as any)
const AuthenticatedStudentSubjectsSubjectIdRoute =
  AuthenticatedStudentSubjectsSubjectIdRouteImport.update({
    id: '/subjects/$subjectId',
    path: '/subjects/$subjectId',
    getParentRoute: () => AuthenticatedStudentRoute,
  } as any)
const AuthenticatedStudentDiagnosticSessionIdRoute =
  AuthenticatedStudentDiagnosticSessionIdRouteImport.update({
    id: '/$sessionId',
    path: '/$sessionId',
    getParentRoute: () => AuthenticatedStudentDiagnosticRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/student': typeof AuthenticatedStudentRouteWithChildren
  '/teacher': typeof AuthenticatedTeacherRouteWithChildren
  '/lesson/$lessonId': typeof AuthenticatedLessonLessonIdRoute
  '/student/assistant': typeof AuthenticatedStudentAssistantRoute
  '/student/calendar': typeof AuthenticatedStudentCalendarRoute
  '/student/diagnostic': typeof AuthenticatedStudentDiagnosticRouteWithChildren
  '/student/lessons': typeof AuthenticatedStudentLessonsRoute
  '/student/materials': typeof AuthenticatedStudentMaterialsRoute
  '/student/path': typeof AuthenticatedStudentPathRoute
  '/student/progress': typeof AuthenticatedStudentProgressRoute
  '/teacher/analytics': typeof AuthenticatedTeacherAnalyticsRoute
  '/teacher/assistant': typeof AuthenticatedTeacherAssistantRoute
  '/teacher/diagnostic': typeof AuthenticatedTeacherDiagnosticRoute
  '/teacher/materials': typeof AuthenticatedTeacherMaterialsRoute
  '/teacher/plans': typeof AuthenticatedTeacherPlansRoute
  '/student/': typeof AuthenticatedStudentIndexRoute
  '/teacher/': typeof AuthenticatedTeacherIndexRoute
  '/student/diagnostic/$sessionId': typeof AuthenticatedStudentDiagnosticSessionIdRoute
  '/student/subjects/$subjectId': typeof AuthenticatedStudentSubjectsSubjectIdRoute
  '/student/topics/$topicId': typeof AuthenticatedStudentTopicsTopicIdRoute
  '/teacher/students/$studentId': typeof AuthenticatedTeacherStudentsStudentIdRoute
  '/teacher/students/': typeof AuthenticatedTeacherStudentsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/': typeof AuthenticatedIndexRoute
  '/lesson/$lessonId': typeof AuthenticatedLessonLessonIdRoute
  '/student/assistant': typeof AuthenticatedStudentAssistantRoute
  '/student/calendar': typeof AuthenticatedStudentCalendarRoute
  '/student/diagnostic': typeof AuthenticatedStudentDiagnosticRouteWithChildren
  '/student/lessons': typeof AuthenticatedStudentLessonsRoute
  '/student/materials': typeof AuthenticatedStudentMaterialsRoute
  '/student/path': typeof AuthenticatedStudentPathRoute
  '/student/progress': typeof AuthenticatedStudentProgressRoute
  '/teacher/analytics': typeof AuthenticatedTeacherAnalyticsRoute
  '/teacher/assistant': typeof AuthenticatedTeacherAssistantRoute
  '/teacher/diagnostic': typeof AuthenticatedTeacherDiagnosticRoute
  '/teacher/materials': typeof AuthenticatedTeacherMaterialsRoute
  '/teacher/plans': typeof AuthenticatedTeacherPlansRoute
  '/student': typeof AuthenticatedStudentIndexRoute
  '/teacher': typeof AuthenticatedTeacherIndexRoute
  '/student/diagnostic/$sessionId': typeof AuthenticatedStudentDiagnosticSessionIdRoute
  '/student/subjects/$subjectId': typeof AuthenticatedStudentSubjectsSubjectIdRoute
  '/student/topics/$topicId': typeof AuthenticatedStudentTopicsTopicIdRoute
  '/teacher/students/$studentId': typeof AuthenticatedTeacherStudentsStudentIdRoute
  '/teacher/students': typeof AuthenticatedTeacherStudentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/student': typeof AuthenticatedStudentRouteWithChildren
  '/_authenticated/teacher': typeof AuthenticatedTeacherRouteWithChildren
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/lesson/$lessonId': typeof AuthenticatedLessonLessonIdRoute
  '/_authenticated/student/assistant': typeof AuthenticatedStudentAssistantRoute
  '/_authenticated/student/calendar': typeof AuthenticatedStudentCalendarRoute
  '/_authenticated/student/diagnostic': typeof AuthenticatedStudentDiagnosticRouteWithChildren
  '/_authenticated/student/lessons': typeof AuthenticatedStudentLessonsRoute
  '/_authenticated/student/materials': typeof AuthenticatedStudentMaterialsRoute
  '/_authenticated/student/path': typeof AuthenticatedStudentPathRoute
  '/_authenticated/student/progress': typeof AuthenticatedStudentProgressRoute
  '/_authenticated/teacher/analytics': typeof AuthenticatedTeacherAnalyticsRoute
  '/_authenticated/teacher/assistant': typeof AuthenticatedTeacherAssistantRoute
  '/_authenticated/teacher/diagnostic': typeof AuthenticatedTeacherDiagnosticRoute
  '/_authenticated/teacher/materials': typeof AuthenticatedTeacherMaterialsRoute
  '/_authenticated/teacher/plans': typeof AuthenticatedTeacherPlansRoute
  '/_authenticated/student/': typeof AuthenticatedStudentIndexRoute
  '/_authenticated/teacher/': typeof AuthenticatedTeacherIndexRoute
  '/_authenticated/student/diagnostic/$sessionId': typeof AuthenticatedStudentDiagnosticSessionIdRoute
  '/_authenticated/student/subjects/$subjectId': typeof AuthenticatedStudentSubjectsSubjectIdRoute
  '/_authenticated/student/topics/$topicId': typeof AuthenticatedStudentTopicsTopicIdRoute
  '/_authenticated/teacher/students/$studentId': typeof AuthenticatedTeacherStudentsStudentIdRoute
  '/_authenticated/teacher/students/': typeof AuthenticatedTeacherStudentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/onboarding'
    | '/profile'
    | '/student'
    | '/teacher'
    | '/lesson/$lessonId'
    | '/student/assistant'
    | '/student/calendar'
    | '/student/diagnostic'
    | '/student/lessons'
    | '/student/materials'
    | '/student/path'
    | '/student/progress'
    | '/teacher/analytics'
    | '/teacher/assistant'
    | '/teacher/diagnostic'
    | '/teacher/materials'
    | '/teacher/plans'
    | '/student/'
    | '/teacher/'
    | '/student/diagnostic/$sessionId'
    | '/student/subjects/$subjectId'
    | '/student/topics/$topicId'
    | '/teacher/students/$studentId'
    | '/teacher/students/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/onboarding'
    | '/profile'
    | '/'
    | '/lesson/$lessonId'
    | '/student/assistant'
    | '/student/calendar'
    | '/student/diagnostic'
    | '/student/lessons'
    | '/student/materials'
    | '/student/path'
    | '/student/progress'
    | '/teacher/analytics'
    | '/teacher/assistant'
    | '/teacher/diagnostic'
    | '/teacher/materials'
    | '/teacher/plans'
    | '/student'
    | '/teacher'
    | '/student/diagnostic/$sessionId'
    | '/student/subjects/$subjectId'
    | '/student/topics/$topicId'
    | '/teacher/students/$studentId'
    | '/teacher/students'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/onboarding'
    | '/_authenticated/profile'
    | '/_authenticated/student'
    | '/_authenticated/teacher'
    | '/_authenticated/'
    | '/_authenticated/lesson/$lessonId'
    | '/_authenticated/student/assistant'
    | '/_authenticated/student/calendar'
    | '/_authenticated/student/diagnostic'
    | '/_authenticated/student/lessons'
    | '/_authenticated/student/materials'
    | '/_authenticated/student/path'
    | '/_authenticated/student/progress'
    | '/_authenticated/teacher/analytics'
    | '/_authenticated/teacher/assistant'
    | '/_authenticated/teacher/diagnostic'
    | '/_authenticated/teacher/materials'
    | '/_authenticated/teacher/plans'
    | '/_authenticated/student/'
    | '/_authenticated/teacher/'
    | '/_authenticated/student/diagnostic/$sessionId'
    | '/_authenticated/student/subjects/$subjectId'
    | '/_authenticated/student/topics/$topicId'
    | '/_authenticated/teacher/students/$studentId'
    | '/_authenticated/teacher/students/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/teacher': {
      id: '/_authenticated/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof AuthenticatedTeacherRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/student': {
      id: '/_authenticated/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof AuthenticatedStudentRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/teacher/': {
      id: '/_authenticated/teacher/'
      path: '/'
      fullPath: '/teacher/'
      preLoaderRoute: typeof AuthenticatedTeacherIndexRouteImport
      parentRoute: typeof AuthenticatedTeacherRoute
    }
    '/_authenticated/student/': {
      id: '/_authenticated/student/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof AuthenticatedStudentIndexRouteImport
      parentRoute: typeof AuthenticatedStudentRoute
    }
    '/_authenticated/teacher/plans': {
      id: '/_authenticated/teacher/plans'
      path: '/plans'
      fullPath: '/teacher/plans'
      preLoaderRoute: typeof AuthenticatedTeacherPlansRouteImport
      parentRoute: typeof AuthenticatedTeacherRoute
    }
    '/_authenticated/teacher/materials': {
      id: '/_authenticated/teacher/materials'
      path: '/materials'
      fullPath: '/teacher/materials'
      preLoaderRoute: typeof AuthenticatedTeacherMaterialsRouteImport
      parentRoute: typeof AuthenticatedTeacherRoute
    }
    '/_authenticated/teacher/diagnostic': {
      id: '/_authenticated/teacher/diagnostic'
      path: '/diagnostic'
      fullPath: '/teacher/diagnostic'
      preLoaderRoute: typeof AuthenticatedTeacherDiagnosticRouteImport
      parentRoute: typeof AuthenticatedTeacherRoute
    }
    '/_authenticated/teacher/assistant': {
      id: '/_authenticated/teacher/assistant'
      path: '/assistant'
      fullPath: '/teacher/assistant'
      preLoaderRoute: typeof AuthenticatedTeacherAssistantRouteImport
      parentRoute: typeof AuthenticatedTeacherRoute
    }
    '/_authenticated/teacher/analytics': {
      id: '/_authenticated/teacher/analytics'
      path: '/analytics'
      fullPath: '/teacher/analytics'
      preLoaderRoute: typeof AuthenticatedTeacherAnalyticsRouteImport
      parentRoute: typeof AuthenticatedTeacherRoute
    }
    '/_authenticated/student/progress': {
      id: '/_authenticated/student/progress'
      path: '/progress'
      fullPath: '/student/progress'
      preLoaderRoute: typeof AuthenticatedStudentProgressRouteImport
      parentRoute: typeof AuthenticatedStudentRoute
    }
    '/_authenticated/student/path': {
      id: '/_authenticated/student/path'
      path: '/path'
      fullPath: '/student/path'
      preLoaderRoute: typeof AuthenticatedStudentPathRouteImport
      parentRoute: typeof AuthenticatedStudentRoute
    }
    '/_authenticated/student/materials': {
      id: '/_authenticated/student/materials'
      path: '/materials'
      fullPath: '/student/materials'
      preLoaderRoute: typeof AuthenticatedStudentMaterialsRouteImport
      parentRoute: typeof AuthenticatedStudentRoute
    }
    '/_authenticated/student/lessons': {
      id: '/_authenticated/student/lessons'
      path: '/lessons'
      fullPath: '/student/lessons'
      preLoaderRoute: typeof AuthenticatedStudentLessonsRouteImport
      parentRoute: typeof AuthenticatedStudentRoute
    }
    '/_authenticated/student/diagnostic': {
      id: '/_authenticated/student/diagnostic'
      path: '/diagnostic'
      fullPath: '/student/diagnostic'
      preLoaderRoute: typeof AuthenticatedStudentDiagnosticRouteImport
      parentRoute: typeof AuthenticatedStudentRoute
    }
    '/_authenticated/student/calendar': {
      id: '/_authenticated/student/calendar'
      path: '/calendar'
      fullPath: '/student/calendar'
      preLoaderRoute: typeof AuthenticatedStudentCalendarRouteImport
      parentRoute: typeof AuthenticatedStudentRoute
    }
    '/_authenticated/student/assistant': {
      id: '/_authenticated/student/assistant'
      path: '/assistant'
      fullPath: '/student/assistant'
      preLoaderRoute: typeof AuthenticatedStudentAssistantRouteImport
      parentRoute: typeof AuthenticatedStudentRoute
    }
    '/_authenticated/lesson/$lessonId': {
      id: '/_authenticated/lesson/$lessonId'
      path: '/lesson/$lessonId'
      fullPath: '/lesson/$lessonId'
      preLoaderRoute: typeof AuthenticatedLessonLessonIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/teacher/students/': {
      id: '/_authenticated/teacher/students/'
      path: '/students'
      fullPath: '/teacher/students/'
      preLoaderRoute: typeof AuthenticatedTeacherStudentsIndexRouteImport
      parentRoute: typeof AuthenticatedTeacherRoute
    }
    '/_authenticated/teacher/students/$studentId': {
      id: '/_authenticated/teacher/students/$studentId'
      path: '/students/$studentId'
      fullPath: '/teacher/students/$studentId'
      preLoaderRoute: typeof AuthenticatedTeacherStudentsStudentIdRouteImport
      parentRoute: typeof AuthenticatedTeacherRoute
    }
    '/_authenticated/student/topics/$topicId': {
      id: '/_authenticated/student/topics/$topicId'
      path: '/topics/$topicId'
      fullPath: '/student/topics/$topicId'
      preLoaderRoute: typeof AuthenticatedStudentTopicsTopicIdRouteImport
      parentRoute: typeof AuthenticatedStudentRoute
    }
    '/_authenticated/student/subjects/$subjectId': {
      id: '/_authenticated/student/subjects/$subjectId'
      path: '/subjects/$subjectId'
      fullPath: '/student/subjects/$subjectId'
      preLoaderRoute: typeof AuthenticatedStudentSubjectsSubjectIdRouteImport
      parentRoute: typeof AuthenticatedStudentRoute
    }
    '/_authenticated/student/diagnostic/$sessionId': {
      id: '/_authenticated/student/diagnostic/$sessionId'
      path: '/$sessionId'
      fullPath: '/student/diagnostic/$sessionId'
      preLoaderRoute: typeof AuthenticatedStudentDiagnosticSessionIdRouteImport
      parentRoute: typeof AuthenticatedStudentDiagnosticRoute
    }
  }
}

interface AuthenticatedStudentDiagnosticRouteChildren {
  AuthenticatedStudentDiagnosticSessionIdRoute: typeof AuthenticatedStudentDiagnosticSessionIdRoute
}

const AuthenticatedStudentDiagnosticRouteChildren: AuthenticatedStudentDiagnosticRouteChildren =
  {
    AuthenticatedStudentDiagnosticSessionIdRoute:
      AuthenticatedStudentDiagnosticSessionIdRoute,
  }

const AuthenticatedStudentDiagnosticRouteWithChildren =
  AuthenticatedStudentDiagnosticRoute._addFileChildren(
    AuthenticatedStudentDiagnosticRouteChildren,
  )

interface AuthenticatedStudentRouteChildren {
  AuthenticatedStudentAssistantRoute: typeof AuthenticatedStudentAssistantRoute
  AuthenticatedStudentCalendarRoute: typeof AuthenticatedStudentCalendarRoute
  AuthenticatedStudentDiagnosticRoute: typeof AuthenticatedStudentDiagnosticRouteWithChildren
  AuthenticatedStudentLessonsRoute: typeof AuthenticatedStudentLessonsRoute
  AuthenticatedStudentMaterialsRoute: typeof AuthenticatedStudentMaterialsRoute
  AuthenticatedStudentPathRoute: typeof AuthenticatedStudentPathRoute
  AuthenticatedStudentProgressRoute: typeof AuthenticatedStudentProgressRoute
  AuthenticatedStudentIndexRoute: typeof AuthenticatedStudentIndexRoute
  AuthenticatedStudentSubjectsSubjectIdRoute: typeof AuthenticatedStudentSubjectsSubjectIdRoute
  AuthenticatedStudentTopicsTopicIdRoute: typeof AuthenticatedStudentTopicsTopicIdRoute
}

const AuthenticatedStudentRouteChildren: AuthenticatedStudentRouteChildren = {
  AuthenticatedStudentAssistantRoute: AuthenticatedStudentAssistantRoute,
  AuthenticatedStudentCalendarRoute: AuthenticatedStudentCalendarRoute,
  AuthenticatedStudentDiagnosticRoute:
    AuthenticatedStudentDiagnosticRouteWithChildren,
  AuthenticatedStudentLessonsRoute: AuthenticatedStudentLessonsRoute,
  AuthenticatedStudentMaterialsRoute: AuthenticatedStudentMaterialsRoute,
  AuthenticatedStudentPathRoute: AuthenticatedStudentPathRoute,
  AuthenticatedStudentProgressRoute: AuthenticatedStudentProgressRoute,
  AuthenticatedStudentIndexRoute: AuthenticatedStudentIndexRoute,
  AuthenticatedStudentSubjectsSubjectIdRoute:
    AuthenticatedStudentSubjectsSubjectIdRoute,
  AuthenticatedStudentTopicsTopicIdRoute:
    AuthenticatedStudentTopicsTopicIdRoute,
}

const AuthenticatedStudentRouteWithChildren =
  AuthenticatedStudentRoute._addFileChildren(AuthenticatedStudentRouteChildren)

interface AuthenticatedTeacherRouteChildren {
  AuthenticatedTeacherAnalyticsRoute: typeof AuthenticatedTeacherAnalyticsRoute
  AuthenticatedTeacherAssistantRoute: typeof AuthenticatedTeacherAssistantRoute
  AuthenticatedTeacherDiagnosticRoute: typeof AuthenticatedTeacherDiagnosticRoute
  AuthenticatedTeacherMaterialsRoute: typeof AuthenticatedTeacherMaterialsRoute
  AuthenticatedTeacherPlansRoute: typeof AuthenticatedTeacherPlansRoute
  AuthenticatedTeacherIndexRoute: typeof AuthenticatedTeacherIndexRoute
  AuthenticatedTeacherStudentsStudentIdRoute: typeof AuthenticatedTeacherStudentsStudentIdRoute
  AuthenticatedTeacherStudentsIndexRoute: typeof AuthenticatedTeacherStudentsIndexRoute
}

const AuthenticatedTeacherRouteChildren: AuthenticatedTeacherRouteChildren = {
  AuthenticatedTeacherAnalyticsRoute: AuthenticatedTeacherAnalyticsRoute,
  AuthenticatedTeacherAssistantRoute: AuthenticatedTeacherAssistantRoute,
  AuthenticatedTeacherDiagnosticRoute: AuthenticatedTeacherDiagnosticRoute,
  AuthenticatedTeacherMaterialsRoute: AuthenticatedTeacherMaterialsRoute,
  AuthenticatedTeacherPlansRoute: AuthenticatedTeacherPlansRoute,
  AuthenticatedTeacherIndexRoute: AuthenticatedTeacherIndexRoute,
  AuthenticatedTeacherStudentsStudentIdRoute:
    AuthenticatedTeacherStudentsStudentIdRoute,
  AuthenticatedTeacherStudentsIndexRoute:
    AuthenticatedTeacherStudentsIndexRoute,
}

const AuthenticatedTeacherRouteWithChildren =
  AuthenticatedTeacherRoute._addFileChildren(AuthenticatedTeacherRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedStudentRoute: typeof AuthenticatedStudentRouteWithChildren
  AuthenticatedTeacherRoute: typeof AuthenticatedTeacherRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedLessonLessonIdRoute: typeof AuthenticatedLessonLessonIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedStudentRoute: AuthenticatedStudentRouteWithChildren,
  AuthenticatedTeacherRoute: AuthenticatedTeacherRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedLessonLessonIdRoute: AuthenticatedLessonLessonIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
